version: '3.9'

services:
  ubuntu-ytdlp:
    image: ubuntu:latest
    volumes:
      - ./output:/usr/src/app/output
    stdin_open: true
    tty: true
    command: /bin/bash
    working_dir: /usr/src/app
    ports:
      - "8080:8080"  # Example port mapping if needed
