services:
  music-dl:
    image: music-dl:latest
    volumes:
      - ./output:/usr/src/app/output
      - ./input:/usr/src/app/input
    stdin_open: true
    tty: true
    ports:
      - "8080:8080" # Example port mapping if needed
